import TestProvider from "@/app/TestProvider";
import {Nanum_Gothic} from "next/font/google"
import "./styles/globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { MSWComponent } from "@/mocks/MSWComponet";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const FontStyle = Nanum_Gothic({
    weight: ['400'],
    subsets: ['latin'],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={FontStyle.className}>
        <MSWComponent>
          <TestProvider>
            {children}
          </TestProvider>
        </MSWComponent>
      </body>
    </html>
  )
}