import TestProvider from "@/app/TestProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <TestProvider >
        <html lang="en">
            <body>{children}</body>
        </html>
      </TestProvider>
  )
}